### PR TITLE
add license to hiw-api

### PR DESCRIPTION
**Pull request by honestree**
https://github.com/HealthIndicators/js-api/blob/master/LICENSE.md

### CODE REVIEW

**Comment by honestree** [comment]
@x09326 
#5500 
another license adding of hiw-api
please help me review it!

**Comment by x09326** [comment]
Hi @honestree 
You send pull request to the wrong place.
You need to send to cdnjs/cdnjs, not your fork cdnjs.

**Comment by honestree** [comment]
@x09326 
should I send another pull request to cdnjs/cdnjs ?

**Comment by x09326** [comment]
@honestree 
Right!

**Pull request closed without merging**
